# ---------------------
# Versions
# ---------------------
[versions]
agp = "8.11.1"
build-gradle = "8.11.1"
kotlin-gradle-plugin = "2.1.0"
kotlin-gradle-plugin-version = "2.1.0"
kotlin-stdlib = "2.1.0"
navigation-plugin-version = "2.9.2"
dagger = "2.57"
hilt = "2.52"
retrofit = "3.0.0"
room = "2.7.2"
moshi = "1.15.2"

rxkotlin = "3.0.1"
rxjava = "3.1.11"
rxandroid = "3.0.2"
design = "28.0.0"
androidx-core-ktx = "1.16.0"
androidx-junit = "1.2.1"
androidx-espresso = "3.6.1"
androidx-paging = "3.2.1"
androidx-cardvew = "1.0.0"
androidx-fragment = "1.8.8"
androidx-recyclerview = "1.4.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-constraintlayout = "2.2.1"
androidx-preference = "1.2.1"
androidx-appcompat = "1.7.1"
androidx-lifecycle = "2.2.0"

material = "1.12.0" # Stable (https://stackoverflow.com/questions/74191324/cant-determine-type-for-tag-macro-name-m3-comp-bottom-app-bar-container-colo)
pallete = "31.0.0"
multidex = "2.0.1"
navigation = "2.9.2"
picasso = "2.71828"
skeleton = "1.1.2"
mapbox = "11.17.1"
mapbox-search = "2.17.1"
mapbox-navigation = "3.17.1"
play-services-location = "21.3.0"

# Tests
jacoco = "0.8.13"
junit = "4.13.2"
mockk = "1.14.5"
stetho = "1.6.0"

# ---------------------
# Plugins
# ---------------------
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-stdlib" }
android-kotlin-gradle-plugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# ---------------------
# Libraries
# ---------------------
[libraries]


# ---------------------
# DI
# ---------------------
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

# ---------------------
# Networking
# ---------------------
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# ---------------------
# RxJava
# ---------------------
rxkotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rxkotlin" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }

# ---------------------
# Room
# ---------------------
room-rxjava = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# ---------------------
# Moshi
# ---------------------
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }

# ---------------------
# Unit Test
# ---------------------
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
jacoco-agent = { group = "org.jacoco", name = "org.jacoco.agent", version.ref = "jacoco" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }


# ---------------------
# UI
# ---------------------
design = { group = "com.android.support", name = "design", version.ref = "design" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
pallete = { group = "com.android.support", name = "palette-v7", version.ref = "pallete" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
skeleton = { group = "com.github.ethanhua", name = "skeleton", version.ref = "skeleton" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }


# ---------------------
# Mapbox
# ---------------------
mapbox-maps = { group = "com.mapbox.maps", name = "android", version.ref = "mapbox" }
mapbox-search-place-autocomplete = { group = "com.mapbox.search", name = "place-autocomplete", version.ref = "mapbox-search" }
mapbox-search-discover = { group = "com.mapbox.search", name = "discover", version.ref = "mapbox-search" }
mapbox-search-autofill = { group = "com.mapbox.search", name = "autofill", version.ref = "mapbox-search" }
mapbox-search-android-ui = { group = "com.mapbox.search", name = "mapbox-search-android-ui", version.ref = "mapbox-search" }
mapbox-search-android = { group = "com.mapbox.search", name = "mapbox-search-android", version.ref = "mapbox-search" }
mapbox-navigation-android = { group = "com.mapbox.navigationcore", name = "android", version.ref = "mapbox-navigation" }

# ---------------------
# Android X
# ---------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-paging-rxjava = { group = "androidx.paging", name = "paging-rxjava3", version.ref = "androidx-paging" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardvew" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }

androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

# ---------------------
# Navigation
# ---------------------
navigation-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-plugin-version" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }

# ---------------------
# Build Gradle
# ---------------------
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "build-gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin-version" }
multidex = { group = "com.android.support", name = "multidex", version.ref = "multidex" }
stetho = { group = "com.facebook.stetho", name = "stetho", version.ref = "stetho" }
